### ISSUE TITLE
"msg": "Unsupported parameters for (sros_command)  Errors messages commands

### ISSUE THREAD

**Issue by davidf07** [davidf07/Ansible-With-Sros-Nokia-Alcatel-lucent-#1]
"Sros" have an unsupported message: "Sros" is not working with all commands event change the platform.
 NB: Please, I am new to this issue and to GitHub, I need your help to fix this unsupport sros_command or sros_config command cli.

[root@centos7v810-telhsnet Ansible_Runtest]# **### **ansible --version****
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Apr  1 2019, 19:01:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@centos7v810-telhsnet Ansible_Runtest]# 

[root@centos7v810-telhsnet Ansible_Runtest]# 
[Sros_Alu_Log_git.zip](https://github.com/davidf07/Ansible-With-Sros-Nokia-Alcatel-lucent-/files/3035942/Sros_Alu_Log_git.zip)

 hostnametcl
bash: hostnametcl: command not found...
Similar command is: 'hostnamectl'
[root@centos7v810-telhsnet Ansible_Runtest]# hostnamectl
   Static hostname: centos7v810-telhsnet
   Pretty hostname: centos7v810.telhsnet
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 2e395367e57f49f58bdca78d1778257a
           Boot ID: 3d35d4f17f60479cb665474468ff9d35
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.10.1.el7.x86_64
      Architecture: x86-64
[root@centos7v810-telhsnet Ansible_Runtest]# 

fatal: [RT12]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authorize": true,
            "commands": "show version - show version - show bof - show router interface - show router interface - show router bgp summary all - exist all"
        }
    },
    "msg": "Unsupported parameters for (sros_command) module: authorize Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"
}
fatal: [RT08]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authorize": true,
            "commands": "show version - show version - show bof - show router interface - show router interface - show router bgp summary all - exist all"
        }
    },
    "msg": "Unsupported parameters for (sros_command) module: authorize Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"

**Comment by davidf07** [comment]
ansible RT12 -m ping -u Sam-User
RT12 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
[root@centos7v810-telhsnet Nokia]#

**Comment by davidf07** [comment]
TASK [run show Display commands for sros Routers] **************************************************************************************
fatal: [RT06]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sros_command) module: authorize, ignore_errors, parents, register Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"}
fatal: [RT02]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sros_command) module: authorize, ignore_errors, parents, register Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"}
fatal: [RT05]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sros_command) module: authorize, ignore_errors, parents, register Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"}
fatal: [RT01]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (sros_command) module: authorize, ignore_errors, parents, register Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"}

**Comment by davidf07** [comment]
please, help
@arunkaithe
@Jufni Rizada Ramirez
@Chris Sattinger
@James Cammarata jimi-c
@Mandar Sawant
@Dag Wieers 
@trishnaguha

**Comment by davidf07** [comment]
@Salman1485
@privateip
 @gundalow

**Comment by gundalow** [comment]
Did you mean to open this in github.com/ansible/ansible instead? 

Please complete the bug report form via 
https://github.com/ansible/ansible/issues/new/choose


Also https://docs.ansible.com/ansible/latest/network/ has a getting started guide.

**Comment by gundalow** [comment]
The error message implies your playbook is incorrect and you've specified an option that isn't accepted by the module,remove `authorize`  from the failing task and see if that works.

**Comment by davidf07** [comment]
Thank you very much for the support, I am very new in Ansible, I very appreciated all help and support. 
Ok let me remove the authorize and see again, I haven't it before, but look like the same.

**Comment by davidf07** [comment]
ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = ~/.ansible/cp
COLOR_CHANGED(/etc/ansible/ansible.cfg) = yellow
COLOR_DEBUG(/etc/ansible/ansible.cfg) = dark gray
COLOR_DEPRECATE(/etc/ansible/ansible.cfg) = purple
COLOR_DIFF_ADD(/etc/ansible/ansible.cfg) = green
COLOR_ERROR(/etc/ansible/ansible.cfg) = red
COLOR_HIGHLIGHT(/etc/ansible/ansible.cfg) = white
COLOR_OK(/etc/ansible/ansible.cfg) = green
COLOR_UNREACHABLE(/etc/ansible/ansible.cfg) = red
COLOR_VERBOSE(/etc/ansible/ansible.cfg) = blue
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/sh
DEFAULT_FORCE_HANDLERS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /root/.ansible/tmp/ansible-local-449201gkpqpg1
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 2000
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
ERROR_ON_MISSING_HANDLER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
NETWORK_GROUP_MODULES(/etc/ansible/ansible.cfg) = ['sros']
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 50
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = True

**Comment by davidf07** [comment]
The #authorize: yes is remove but still have unsupport Msg issue:
<172.27.27.62> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1554321203.6437552-170818997755714/ /root/.ansible/tmp/ansible-tmp-1554321203.6437552-170818997755714/AnsiballZ_sros_command.py && sleep 0'
<172.27.27.62> EXEC /bin/sh -c '/usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1554321203.6437552-170818997755714/AnsiballZ_sros_command.py && sleep 0'
<172.27.27.62> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1554321203.6437552-170818997755714/ > /dev/null 2>&1 && sleep 0'
fatal: [RT12]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "commands": "show version - show version - show bof - show router interface - show router interface - show router bgp summary all - exist all",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "Vmware_vm_Shell": null,
                "ansible_network_os": "sros",
                "become": true,
                "become_flags": "-s /bin/sh",
                "become_user": "Sam-User",
                "check_mode": false,
                "connection": "cli",
                "gather_facts": true,
                "host": "RT12",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "username": "Sam-User",
                "vm_shell": "/bin/sleep",
                "vm_shell_arg": 100,
                "wait_for_process": true
            },
            "username": "Sam-User"
        }
    },
    "msg": "Unsupported parameters for (sros_command) module: auth_pass Supported parameters include: commands, host, interval, match, password, port, provider, retries, ssh_keyfile, timeout, username, wait_for"
}
        to retry, use: --limit @/etc/Ansible_Playbooks/Nokia/compus105.k007-02T02_GG05VSS03A03.retry

PLAY RECAP **********************************************************************************************************************
RT02                       : ok=1    changed=0    unreachable=0    failed=1   
RT04                       : ok=1    changed=0    unreachable=0    failed=1   
RT05                       : ok=1    changed=0    unreachable=0    failed=1   
RT06                       : ok=1    changed=0    unreachable=0    failed=1   
RT07                       : ok=1    changed=0    unreachable=0    failed=1   
RT08                       : ok=1    changed=0    unreachable=0    failed=1   
RT12                       : ok=1    changed=0    unreachable=0    failed=1   


[ansible_After_Remove Authirze.log](https://github.com/davidf07/Ansible-With-Sros-Nokia-Alcatel-lucent-/files/3040520/ansible_After_Remove.Authirze.log)
[040319_Msg_Unsupport_after remove Auth.zip](https://github.com/davidf07/Ansible-With-Sros-Nokia-Alcatel-lucent-/files/3040526/040319_Msg_Unsupport_after.remove.Auth.zip)

**Comment by davidf07** [comment]
Still not work , and also with raw commad:

ansible Nokia7750 -m raw -a "show version" -u Sam-User -k
SSH password: 
RT01 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT02 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT03 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT04 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT05 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT06 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT07 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT08 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT09 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
RT12 | FAILED | rc=127 >>
/bin/sh: show: command not found
non-zero return code
[root@centos7v810-telhsnet Nokia]#

**Comment by davidf07** [comment]
these commands are fine successful, but the raw command with show version return with errors.


[root@centos7v810]# cat Ansible_Runtest_PBook_GG05_Nokia_Net_CLI_dtest00SSAT239_B.cfg
ansible-playbook 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Apr  1 2019, 16:15:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected

PLAYBOOK: compus105.k007-02T02_GG05VSS03A03B02.yaml *************************************************************************************************************
1 plays in compus105.k007-02T02_GG05VSS03A03B02.yaml

PLAY [Nokia platform 7750SR] ************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************
task path: /etc/Ansible_Playbooks/Nokia/compus105.k007-02T02_GG05VSS03A03B02.yaml:5
ok: [15RT01]
ok: [15RT03]
ok: [15RT05]
ok: [15RT04]
ok: [15RT02]
fatal: [15RT09]: FAILED! => {"msg": "[Errno None] Unable to connect to port 22 on 172.27.27.89"}
ok: [15RT06]
ok: [15RT07]
ok: [15RT12]
ok: [15RT08]
META: ran handlers

TASK [run show Display commands for sros Routers] ***************************************************************************************************************
task path: /etc/Ansible_Playbooks/Nokia/compus105.k007-02T02_GG05VSS03A03B02.yaml:52
fatal: [15RT02]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT02# ", "rc": -32603}
fatal: [15RT01]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT01# ", "rc": -32603}
fatal: [15RT05]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT05# ", "rc": -32603}
fatal: [15RT03]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT03# ", "rc": -32603}
fatal: [15RT04]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT04# ", "rc": -32603}
fatal: [15RT06]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT06# ", "rc": -32603}
fatal: [15RT07]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT07# ", "rc": -32603}
fatal: [15RT08]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT08# ", "rc": -32603}
fatal: [15RT12]: FAILED! => {"changed": false, "msg": "show version show version show bof show router interface show router interface show router bgp summary all exist all\r\n                       ^\r\nError: Invalid parameter. \r\nA:15RT12# ", "rc": -32603}
        to retry, use: --limit @/etc/Ansible_Playbooks/Nokia/compus105.k007-02T02_GG05VSS03A03B02.retry

PLAY RECAP ******************************************************************************************************************************************************
15RT01                     : ok=1    changed=0    unreachable=0    failed=1   
15RT02                     : ok=1    changed=0    unreachable=0    failed=1   
15RT03                     : ok=1    changed=0    unreachable=0    failed=1   
15RT04                     : ok=1    changed=0    unreachable=0    failed=1   
15RT05                     : ok=1    changed=0    unreachable=0    failed=1   
15RT06                     : ok=1    changed=0    unreachable=0    failed=1   
15RT07                     : ok=1    changed=0    unreachable=0    failed=1   
15RT08                     : ok=1    changed=0    unreachable=0    failed=1   
15RT09                     : ok=0    changed=0    unreachable=0    failed=1   
15RT12                     : ok=1    changed=0    unreachable=0    failed=1   

[root@Runtest09]#  ansible -m debug -a "var=hostvars['centos7v00']" localhost
localhost | SUCCESS => {
    "hostvars['centos7v00']": ""
}

## This one is ok

[root@centos7v810]#  ansible -m debug -a "var=hostvars['centos7v00']" Nokia7750
15RT01 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT03 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT05 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT04 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT02 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT06 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT08 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT12 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT07 | SUCCESS => {
    "hostvars['centos7v00']": ""
}
15RT09 | FAILED! => {
    "msg": "[Errno None] Unable to connect to port 22 on 172.27.27.89"
}


This one is ok with Raw 

[root@centos7v810]#  ansible -m raw -a "var=hostvars['centos7v00']" Nokia7750
15RT03 | CHANGED | rc=0 >>

15RT04 | CHANGED | rc=0 >>

15RT02 | CHANGED | rc=0 >>

15RT05 | CHANGED | rc=0 >>

15RT01 | CHANGED | rc=0 >>

15RT07 | CHANGED | rc=0 >>

15RT06 | CHANGED | rc=0 >>

15RT12 | CHANGED | rc=0 >>

15RT08 | CHANGED | rc=0 >>

15RT09 | FAILED | rc=-1 >>
[Errno None] Unable to connect to port 22 on 172.27.27.89

##Failed
[root@centos7v810]#  ansible -m raw -a "var=show version['centos7v00']" Nokia7750
15RT05 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT03 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT02 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT01 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT04 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT07 | FAILED | rc=127 >>
/bin/sh: version[centos7v00]: command not found
non-zero return code
15RT09 | FAILED | rc=-1 >>
[Errno None] Unable to connect to port 22 on 172.27.27.89
15RT08 | FAILED | rc=-1 >>
[Errno None] Unable to connect to port 22 on 172.27.27.88
15RT12 | FAILED | rc=-1 >>
[Errno None] Unable to connect to port 22 on 172.27.27.62
15RT06 | FAILED | rc=-1 >>
timed out
[root@centos7v810]

**Comment by davidf07** [comment]
Thank you again for all supports ,  no more errors today after remove  auth_pass and authorise: yes, it is seen like working.
I have  now output:
 "===============================================================================", 
            "MDA Summary", 
            "===============================================================================", 
            "Slot  Mda   Provisioned Type                            Admin     Operational", 
            "                Equipped Type (if different)            State     State", 
            "-------------------------------------------------------------------------------", 
            "1     1     m5-1gb-sfp-b                                up        up", 
            "==============================================================================="
        ], 
        [
            "===============================================================================", 
            "MDA 1/1 detail", 
            "===============================================================================", 
            "Slot  Mda   Provisioned Type                            Admin     Operational", 
            "                Equipped Type (if different)            State     State", 
            "-------------------------------------------------------------------------------", 
            "1     1     m5-1gb-sfp-b                                up        up", 


ok: [T06] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "commands": [
                "show  mda", 
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": null, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": "Sam-User", 
            "wait_for": null

thank  you  for support.

**Comment by davidf07** [comment]
It is work now , thank you all for support.
My case , I have to remove all authorise and authpass from playbook, and it is work fine.

***************************************************************************************************************
ok: [15RT01]
ok: [15RT02]
ok: [15RT05]
ok: [15RT06]
ok: [15RT07]102742fe98c.png)
